export enum ACTION {
  GET_TASKS = 'GET_TASKS',
  GET_TASK = 'GET_TASK',
  GET_TAGS = 'GET_TAGS',
  GET_STATUSES = 'GET_STATUSES',
  GET_NEW_TASK_ID = 'GET_NEW_TASK_ID',
  GET_USERS = 'GET_USERS',
  SET_UPDATE = 'SET_UPDATE',
  SET_STATUS = 'SET_STATUS',
  SET_EXECUTOR = 'SET_EXECUTOR',
  SET_COMMENT = 'SET_COMMENT',
  CREATE_TASK = 'CREATE_TASK',
}
